package View;

import Entity.Carro;
import Entity.Cliente;
import Model.CarroTableModel;
import Repository.CarroRepository;
import Repository.ClienteRepository;
import static View.ModalCarro.jLabelSlcCliente;
import static View.ModalCarro.jTextFieldClienteCpf;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

/*
 *
 * @author lukin
 */
public class GridCarro extends javax.swing.JFrame {

    /**
     * Creates new form ModalCarro
     */
    public GridCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIncluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarro = new javax.swing.JTable();
        jTextFieldFiltroNomeCarro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Disponibilidade da frota");
        setBackground(new java.awt.Color(153, 153, 153));

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        TableCellRenderer RendererData = new DefaultTableCellRenderer() {
            SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
            public Component getTableCellRendererComponent(JTable table,
                Object value, boolean isSelected, boolean hasFocus,
                int row, int column) {
                if(value != null) {
                    Date data = new Date(value.toString().replaceAll("-", "/"));
                    value = f.format(data);
                } else {
                    value = "";
                }
                return super.getTableCellRendererComponent(table, value, isSelected,
                    hasFocus, row, column);
            }
        };
        TableCellRenderer RendererStatus = new DefaultTableCellRenderer() {
            public Component getTableCellRendererComponent(JTable table,
                Object value, boolean isSelected, boolean hasFocus,
                int row, int column) {
                if(value != null) {
                    if(Integer.parseInt(value.toString()) == 0){
                        value = "Disponivel";
                    } else {
                        value = "Locado";
                    }
                } else {
                    value = "";
                }
                return super.getTableCellRendererComponent(table, value, isSelected,
                    hasFocus, row, column);
            }
        };
        CarroTableModel model = new CarroTableModel();
        jTableCarro.setModel(model);
        jTableCarro.getColumnModel().getColumn(6).setCellRenderer(RendererStatus);
        jTableCarro.getColumnModel().getColumn(8).setCellRenderer(RendererData);
        jTableCarro.getColumnModel().getColumn(9).setCellRenderer(RendererData);
        model.addList(new CarroRepository().lista(jTextFieldFiltroNomeCarro.getText()));
        jScrollPane1.setViewportView(jTableCarro);

        jTextFieldFiltroNomeCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFiltroNomeCarroActionPerformed(evt);
            }
        });
        jTextFieldFiltroNomeCarro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFiltroNomeCarroKeyPressed(evt);
            }
        });

        jLabel2.setText("Filtrar por nome:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButtonClientes.setText("Clientes");
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFiltroNomeCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonIncluir)
                        .addComponent(jButtonAlterar)
                        .addComponent(jButtonExcluir)
                        .addComponent(jTextFieldFiltroNomeCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jButtonClientes))
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFiltroNomeCarroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFiltroNomeCarroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            new CarroRepository().atualizaStore(jTextFieldFiltroNomeCarro.getText());
        }
    }//GEN-LAST:event_jTextFieldFiltroNomeCarroKeyPressed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int index = jTableCarro.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(new JFrame(), "Nenhuma linha selecionada!", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            CarroRepository carroRepositoy = new CarroRepository();
            Integer Id = Integer.parseInt(jTableCarro.getModel().getValueAt(index, 0).toString());
            if (JOptionPane.showConfirmDialog(new JFrame(), "Tem certeza que deseja excluir o carro Id: " + Id + "?", "Alerta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
                try {
                    carroRepositoy.excluir(Id);
                } finally {
                    carroRepositoy.atualizaStore("");
                }
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        new ModalCarro().show();
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        int linha = jTableCarro.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(new JFrame(), "Nenhuma linha selecionada!", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            Integer Id = Integer.parseInt(jTableCarro.getModel().getValueAt(linha, 0).toString());
            Carro carro = new CarroRepository().buscaPorId(Id);
            new ModalCarro().show();
            ModalCarro.jLabelId.setText(carro.getId().toString());
            ModalCarro.jTextFieldNome.setText(carro.getNome());
            ModalCarro.jTextFieldMarca.setText(carro.getMarca());
            ModalCarro.jTextFieldChassis.setText(carro.getChassis());
            ModalCarro.jTextFieldPlaca.setText(carro.getPlaca());
            ModalCarro.jTextFieldKilometragem.setText(carro.getKilometragem().toString());
            ModalCarro.jTextFieldValorDiaria.setText(carro.getValorDia().toString());
            SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
            if (carro.getClienteId() != null) {
                ModalCarro.jTextFieldClienteCpf.setText(carro.getClienteId().toString());
            }
            if (carro.getDataRetirada() != null) {
                ModalCarro.jFormattedTextFieldDataRetirada.setText(f.format(carro.getDataRetirada()));
            }
            if (carro.getDataDevolucao() != null) {
                ModalCarro.jFormattedTextFieldDataDevolucao.setText(f.format(carro.getDataDevolucao()));
            }
            Cliente cliente = new ClienteRepository().buscaPorCpf(jTextFieldClienteCpf.getText());
            if (cliente != null) {
                jLabelSlcCliente.setText(cliente.getNome());
            } else {
                jLabelSlcCliente.setText("");
            }
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTextFieldFiltroNomeCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFiltroNomeCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFiltroNomeCarroActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        new GridCliente().setVisible(true);
    }//GEN-LAST:event_jButtonClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GridCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GridCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GridCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GridCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GridCarro().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable jTableCarro;
    private javax.swing.JTextField jTextFieldFiltroNomeCarro;
    // End of variables declaration//GEN-END:variables
}
